### PR TITLE
[WIP] general refactoring and `go_back_to_root` function

### PR DESCRIPTION
**Pull request by joao-vitor-souza**
[00d80fe](https://github.com/Joe91/fun-bots/commit/0dd80fee927589679fcebd955114bb3f35a551a6): removal of temp variables (verbosity matters) and apply of `go_back_to_root` function, general refactor;
[37cdf1b](https://github.com/Joe91/fun-bots/commit/37cdf1bc3bb15aad2f1f099787d7e98e263a26de): vacuum db in `clear_settings.py`;
[a5435f2](https://github.com/Joe91/fun-bots/commit/a5435f228ff5767ddd142f93f5778cc2458aeb16): `go_back_to_root` implementation;
[3a19615](https://github.com/Joe91/fun-bots/pull/241/commits/3a196153ed8e3e135905183a86eb7453f1d2a254): fix broken paths in `create_Settings.py` (`ext/shared` -> `ext/Shared`)
[67ff863](https://github.com/Joe91/fun-bots/commit/67ff8631fa5d83f4c3d360d638d8e2dbf4cf9153), [37765cc](https://github.com/Joe91/fun-bots/pull/241/commits/37765cce405613bf38d4ae7612ffcea6c195ab86) and [1b842b0](https://github.com/Joe91/fun-bots/pull/241/commits/1b842b017bd734d64e48e95e54cc618b4ce1ebc2): working in progress...

### CODE REVIEW

**Comment by Joe91** [comment]
How can we solve the issue, that the module "go_back_to_root" can't be found when using the fun-bots-helper.py ?
Should the tools-scripts work standalone or should we focus on the usage in the fun-bots-helper.py?

**Comment by Joe91** [comment]
By the way: I really like what you are doing! This looks so much better than before :-)... Thanks a lot!

**Comment by joao-vitor-souza** [comment]
> How can we solve the issue, that the module "go_back_to_root" can't be found when using the fun-bots-helper.py ? Should the tools-scripts work standalone or should we focus on the usage in the fun-bots-helper.py?

I created the folder `fun-bots/dev/fun-bots-helper/addons` that contains functions that will modularize all the files in `tools`, now it's working fine. The PR was still in progress and you merged it btw 😅. No need to revert it though (unless you need to use `fun-bots-helper.py` right now), I will soon make another PR.

**Comment by Joe91** [comment]
Ah okay. All fine. I modified the import on some of the files on dev, but I can revert that change. 
You can just push it directly to dev if you are happy with it.
But I'm also fine with merging a RP :-)

**Comment by Joe91** [comment]
Just one proposal: when working on a feature / modification: I think it's best to create a separated Branch for that and try to keep the dev-branch as functional if possible. We can merge back whenever we want but the should also make merging easier when we both develop new features. Of course if it's only a small change just do it directly. And if you prefer to work directly on dev I'm also fine with that 🙂

**Comment by joao-vitor-souza** [comment]
No problem. I test every unit before I commit something directly to `dev`, but a branch dedicated to that is actually the best choice, it maintains the commit history cleaner

**Comment by joao-vitor-souza** [comment]
No problem. I test every unit before I commit something directly to `dev`, but a branch dedicated to that is actually the best choice, it maintains the commit history more concise.

**Comment by Joe91** [comment]
🙂👍

**Comment by Joe91** [comment]
Just fixed a little issue with the windows-paths on the root - module so the fun-bots-helper runs again on windows. Hope you are fine with this "workaround". Really looks much cleaner and nicer this way.

**Pull request merged**
