### PR TITLE
Update cn_CN.lua

### PR DESCRIPTION
**Pull request by LoveMiku233**

### CODE REVIEW

**Comment by Joe91** [comment]
There will be a language-editor some time, so you don't have to do this all by hand. But thank you very much for keeping this updated!!!

**Comment by LoveMiku233** [comment]
My pleasure,Thank you very much for creating this mod

**Comment by LoveMiku233** [comment]
> 会有一个语言编辑器一段时间，所以你不必做这一切手工。但非常感谢你保持更新!!!

My pleasure,Thank you very much for creating this mod

**Comment by LoveMiku233** [comment]
> There will be a language-editor some time, so you don't have to do this all by hand. But thank you very much for keeping this updated!!!

My pleasure,Thank you very much for creating this mod

**Pull request merged**
