### PR TITLE
propose: run `fun-bots-helper` through batch file

### PR DESCRIPTION
**Pull request by joao-vitor-souza**
@Joe91 , I changed the `fun-bots-helper.bat` so it runs the helper from the main folder. Thing is, the user needs to have a Python interpreter > 3.xx to run the batch. `pyinstaller` compiles the script and a whole Python interpreter (and its dependencies) within the executable, so the user is indirectly using a python interpreter. Another option is running `create_exe_file.bat`, move `fun-bots-helper.exe` from `dist` to `fun-bots-helper/` and create a shortcut in the main folder pointing to `dev/fun-bots-helper/fun-bots-helper.exe`.  What's better? I think the latter is much better, but I'm using Xubuntu and I'll have to run a bunch of stuff just to emulate Windows batches, executables and shortcuts. Can you try to do this on your machine? `pyinstaller` creates an executable based on the user's OS, so it'll be much easier if you run it on Windows.

### CODE REVIEW

**Comment by Joe91** [comment]
Ah a good ideas. Yeah I just tried your 2nd proposal and this works just fine on windows. I agree that this is the best solution since most of the users use windows and have now up-to-date python-installation.

**Comment by Joe91** [comment]
So are you fine with that if we close this PR then?

**Comment by joao-vitor-souza** [comment]
> So are you fine with that if we close this PR then?

Ok, I'm going to commit (except build) to dev branch, these are other changes, closing PR...

**Comment by Joe91** [comment]
I already did so when I tested it :-)

**Pull request closed without merging**
