### PR TITLE
Create `test_clear_all_paths` and `test_clear_settings`

### PR DESCRIPTION
**Pull request by joao-vitor-souza**
[0380c4e](https://github.com/Joe91/fun-bots/commit/0380c4e1f81f33cc2a19483914c1c0aa949b9915) and [002cdbc](https://github.com/Joe91/fun-bots/commit/002cdbc127207eb2df46fef45449328be7a06c1f): Create the `tests/` folder for the `tools/` scripts. Eventually, this will be used to automate tests for all tools, therefore, eliminating the necessity of manual testing. Any new change in `tools/` scripts will now be automatically tested running `pytest` in `tests/` folder.
[c7230dc](https://github.com/Joe91/fun-bots/commit/c7230dc5ccd9dbf84ea8a9736da09c4e65b1c729): Add the `__init__.py` to all folders of `fun-bots-helper`. This tells the Python interpreter to treat all folders as Python modules, eliminating the necessity of using `sys.path.insert(1, "../")` to move to a folder up.

Once merged it, I'll commit new tests directly to `dev` branch.

### CODE REVIEW

**Comment by joao-vitor-souza** [comment]
Also, I had to remove `cursor.execute("vacuum")` because this was droping the `sqlite_sequence` table after reconstructing the database, since `sqlite_sequence` was totally cleaned after running `clear_all_paths.py`.

**Comment by Joe91** [comment]
This really is an amazing development. I used the vakuum to reduce the size of the database. But I'm fine with that.
It depends on you if you want to add more tests. Since it's mostly a dev-tool it does not need to be tested in extrem depth, but having this is amazing:-)...

**Comment by joao-vitor-souza** [comment]
> This really is an amazing development. I used the vakuum to reduce the size of the database. But I'm fine with that. It depends on you if you want to add more tests. Since it's mostly a dev-tool it does not need to be tested in extrem depth, but having this is amazing:-)...

Yep, the tests will mostly check if the functions are doing their main task. No need to do more than that for now.

 I don't know if an empty `sqlite_sequence` table is useful for something, maybe I'll use vacuum again and adapt the `test_clear_all_paths.py` to it by removing `sqlite_sequence` table from `remaining_tables`. Do you remember if `sqlite_sequence` is used somewhere else? I don't think so.

**Comment by Joe91** [comment]
Have to check that. But it should be easy to test if everything works still fine. I don't think it's needed to vacuum the files. With the button you only want to remove unwanted tables from the database. No need to shrink the size at all since it will be filled sooner or later anyways...

**Comment by joao-vitor-souza** [comment]
> I'm totally open for all proposals :-) . Just go for it if you like! Another questin: Do you also use discord? That would simplify the communication a little. We have our own fun-bots-discord-server with some dev-channels...

I entered in the server right now. I'm joao-vitor-souza

**Pull request merged**
